# 是否开启快速模式，快速模式下仅测试连通性
fast_mode = false

# 是否开启调试模式，输出详细的日志信息
debug_mode = true

# 待测速的订阅节点
# 支持网络地址 https://xxx
# 支持本地地址（绝对地址）/User/xxx/xx.yml
# 支持单个订阅链接，ss://xxx

#"https://clash.nikaidouyui.top/?name=%E9%A6%99%E6%B8%AF"
#"https://raw.githubusercontent.com/PuddinCat/BestClash/refs/heads/main/proxies.yaml"
#"https://clash.nikaidouyui.top?limit=8",
subs = [
"https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt",
"https://raw.githubusercontent.com/aiboboxx/clashfree/refs/heads/main/clash.yml",
"https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2",
"https://raw.githubusercontent.com/PuddinCat/BestClash/refs/heads/main/proxies.yaml",
"https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml"
]

# 是否重命名节点，打开后会使用 geoip 等方式进行代理真实 IP 和地理地址查询
rename_node = true
rename_pattern = "${COUNTRYCODE}_${CITY}_${ISP}"

# 是否需要加上代理池的节点一起筛选
need_add_pool = false
# 代理节点池
pools = [
    "https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml"
]

# 测试分组大小
test_group_size = 50

# 连通性测试
[connect_test]
url = "http://www.google-analytics.com/generate_204"
expected = 204
timeout = 2000

# 带宽测速配置
[speed_test]
enabled = true
url = "https://speed.cloudflare.com/__down?bytes=10485760"  # 测速文件URL（10MB）
timeout = 15000  # 增加超时时间到15秒
min_speed_mbps = 2.0  # 最小速度阈值（MB/s），低于此速度的节点将被过滤
